---
- name: Raspberry pi setup
  hosts: pi
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - base
    - dump1090
    - flightaware # may require reboot to complete successfully
    - flightradar24 # requires manual configuration, see README
