---
- name: Raspberry pi setup
  hosts: pi
  gather_facts: true
  remote_user: pi
  become: yes
  become_user: root
  roles:
    - base
    - dump1090 # optional manual configuration, see README
    - flightradar24 # requires manual configuration, see README
    - { role: flightaware, when: 'flightaware_userid is defined' } # only run if configured
    - { role: ddclient, when: 'ddclient_userid is defined' } # only run if configured
