- name: Install ddclient package
  tags: install-ddclient-package
  apt: 
    name: "{{ item }}"
    state: present
  with_items: 
    "{{ ddclient_pkg }}"
  when: ( 'ddclient_login' is defined ) and
        ( 'ddclient_password' is defined) and
        ( 'ddclient_domain' is defined )

- name: Check ddclient install
  tags: check-ddclient-install
  stat: 
    path: /usr/sbin/ddclient
  register: ddclient_bin

- name: Template ddclient config 
  tags: template-ddclient-config
  template: 
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  notify: 
    - restart ddclient
  when:
    ddclient_bin.stat is defined
