- name: Install ddclient package
  tags: install-ddclient-package
  apt: 
    name: "{{ item }}"
    state: present
  with_items: 
    "{{ ddclient_pkg }}"

- name: Template ddclient config 
  tags: template-ddclient-config
  template: 
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  notify: 
    - restart ddclient
