---
- name: Add dump1090 key
  tags: add-dump1090-key
  apt_key: 
    keyserver: "{{ dump1090_keyserver }}"
    id: "{{ dump1090_public_key }}"

- name: Add dump1090 repo
  tags: add-dump1090-repo
  apt_repository: 
    repo: "{{ dump1090_repo }}" 
    state: present 
    filename: "{{ dump1090_package }}"

- name: Install dump1090 package
  tags: install-dump1090-package
  apt: 
    name: "{{ dump1090_package }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 600

- name: Install dump1090 extra packages
  tags: install-dump1090-extrapackages
  apt: 
    name: "{{ item }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 3600
  with_items:
    - "{{ dump1090_extra_packages }}"

- name: Enable dump1090 mod
  tags: enable-dump1090-mod
  command: lighttpd-enable-mod dump1090
  args:
    creates: /etc/lighttpd/conf-enabled/89-dump1090.conf
  notify: restart lighttpd

- name: Install dump1090 script
  tags: install-dump1090-script
  template:
    src: dump1090-check.sh.j2
    dest: "/home/pi/dump1090-check.sh"
    owner: pi
    group: pi
    mode: 0755

- name: Install dump1090 cron
  tags: install-dump1090-cron
  copy:
    src: dump1090.cron
    dest: "/etc/cron.d/dump1090-check"
    owner: root
    group: root
    mode: 0644
