- name: Configure local hostname
  tags: configure-local-hostname
  hostname: name="{{ pi_hostname }}"

- name: Test hostname file
  tags: test-hostname-file
  shell: grep "^{{ pi_hostname }}" /etc/hostname
  register: hostname_grep
  ignore_errors: true

- name: Set hostname file
  tags: set-hostname-file
  shell: echo {{ pi_hostname }} > /etc/hostname
  when: hostname_grep.stdout == ""

- name: Test hosts file
  tags: test-hosts-file
  shell: grep "^127.0.1.1[[:space:]]{{ pi_hostname }}" /etc/hosts
  register: hosts_grep
  ignore_errors: true

- name: Update hosts file
  tags: update-hosts-fie
  lineinfile: 
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1.*'
    line: "127.0.1.1\t{{ pi_hostname }}"
    owner: root
    group: root
    mode: 0644
  when: hosts_grep.stdout == ""