- name: Install ssh public keys
  tags: ssh-install-pubkey
  authorized_key:
    user: pi
    key: "{{ lookup('file', item )}}"
  with_fileglob: 
    - "~/.ssh/id_*.pub"
    - "ssh_keys/*.pub"

- name: Set user password
  tags: set-user-password
  user: name=pi password="{{ pi_password }}"
  when: pi_password is defined