---
- name: Install flightaware package
  tags: install-flightaware-package
  apt: 
    deb: "{{ flightaware_url }}/{{ flightaware_package }}"
    state: present
    install_recommends: true
    force: true

- name: Template piaware config 
  tags: template-piaware-config
  template: 
    src: piaware.j2
    dest: /root/.piaware
  notify: 
    - restart flightaware
