---
- name: Install flightaware package
  tags: install-flightaware-package
  apt: 
    deb: "{{ flightaware_url }}/{{ flightaware_package }}"
    state: present
    install_recommends: true
    force: true

- name: Update flightaware config
  tags: update-flightaware-config
  command: piaware-config -autoUpdate 1 -manualUpdate 1 -user {{ flightaware_userid }}
  notify: restart flightaware
  args:
    creates: /root/.piaware
